wandb_version: 1

lr:
  desc: null
  value: 0.001
num_classes:
  desc: null
  value: 157
dataset:
  desc: null
  value: charades
epochs:
  desc: null
  value: '100'
num_summary_tokens:
  desc: null
  value: 32
pretrained_model:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.7.7
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718885980.012169
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.7.7
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
